In [26]:
import numpy as np

Задание №1

In [29]:
a = np.arange(0, 15) 
x = a[::-1]

print(x)
type(x)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


numpy.ndarray

Задание №2

In [57]:
my_diag = np.diag(np.arange(0, 100, 20))
print(my_diag)
np.trace(my_diag) # Сумма значений диагонали

[[ 0  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 40  0  0]
 [ 0  0  0 60  0]
 [ 0  0  0  0 80]]


200

Задание №3

In [64]:
from numpy import linalg

In [71]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [5, 4, 0] ] )
b = np.array( [4, 12, -3] )

In [76]:
x = linalg.solve(a, b)
print(x) # Ответ
np.allclose( np.dot(a, linalg.solve(a,b)), b ) # Проверка

[-5.18181818  5.72727273 13.27272727]


True

Задание №4

In [78]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [79]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [174]:
for i in zip(users_stats):
        aLength = np.linalg.norm( i )
        bLength = np.linalg.norm( next_user_stats )
        x = (np.dot( i, next_user_stats ) / ( aLength * bLength ))
        
        print(x)
    

[0.2]
[0.84515425]
[0.4]
[0.79056942]
[0.4]
[0.]
[0.]
[0.9486833]
[0.]
[0.]
